[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"
  edge_handlers = "netlify/edge-handlers"

[build.environment]
  # Node.js version
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.8.1"
  
  # Build optimizations
  NODE_OPTIONS = "--max_old_space_size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  
  # Next.js specific
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NETLIFY_NEXT_PLUGIN_FORCE_BUILD = "true"
  
  # Build caching
  NETLIFY_BUILD_CACHE = "true"
  
  # Required environment variables (set these in Netlify UI)
  # NEXT_PUBLIC_FIREBASE_API_KEY
  # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  # NEXT_PUBLIC_FIREBASE_PROJECT_ID
  # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  
  # Build settings
  NETLIFY_USE_YARN = "false"
  YARN_VERSION = "1.22.19"
  
  # Enable Next.js ISR
  NETLIFY_NEXT_PLUGIN_USE_NEXT_IMAGE = "true"
  NETLIFY_NEXT_PLUGIN_USE_IMAGE_OPTIMIZER = "true"
  # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  # NEXT_PUBLIC_FIREBASE_APP_ID
  # NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
  # NEXT_PUBLIC_FIREBASE_DATABASE_URL

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicit MIME types for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

[[headers]]
  for = "/*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff"

[[headers]]
  for = "/*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/ttf"

[[headers]]
  for = "/*.eot"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/vnd.ms-fontobject"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# Ensure _next/static files are served with correct MIME types
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
    # Set MIME types based on file extension
    x-content-type-options = "nosniff"
    
    # Set specific MIME types for known file types
    x-frame-options = "SAMEORIGIN"
    x-xss-protection = "1; mode=block"
    
    # Security headers
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"
    
    # HSTS
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    
    # CORS
    Access-Control-Allow-Origin = "*"
    
    # Enable preloading of assets
    Link = "</_next/static/css/3931a2f8ce09e7c4.css>; rel=preload; as=style, </_next/static/css/e5661e8547492e7a.css>; rel=preload; as=style"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
