[build]
  command = "npm run netlify-build"
  publish = ".next"
  functions = ".netlify/functions"
  base = "/"
  base_directory = "/"
  node_version = "18.17.0"
  node_bundler = "esbuild"
  
  # Use Docker image with Node.js 18.17.0
  image = "node:18.17.0"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.0.0"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max_old_space_size=4096"
  NETLIFY_NEXT_PLUGIN_SKIP = "false"
  NETLIFY_NEXT_PLUGIN_FORCE_BUILD = "true"
  
  # Required environment variables (set these in Netlify UI)
  # NEXT_PUBLIC_FIREBASE_API_KEY
  # NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  # NEXT_PUBLIC_FIREBASE_PROJECT_ID
  # NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  # NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  # NEXT_PUBLIC_FIREBASE_APP_ID
  # NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
  # NEXT_PUBLIC_FIREBASE_DATABASE_URL

# Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), interest-cohort=()"

# Cache control for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@netlify/plugin-nextjs"]
